### ISSUE TITLE
Use matchMedia instead of resize event

### ISSUE THREAD

**Issue by aarongarciah** [wednesday-solutions/react-screentype-hook#1]
Hi! I wanted to suggest that this hook performance would be increased a lot by using [`window.matchMedia`](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) instead of `window.addEventListener('resize')`.

Some examples of another hooks:

- https://github.com/streamich/use-media/blob/7b26a10621f423943b6824f5fb9bc0e539803e21/src/useMedia.ts#L28
- https://github.com/lessmess-dev/react-media-hook/blob/03b9e674a04f7292b7f3102b7022cc561a6b7407/index.js#L7

`matchMedia` [is supported even in IE10](https://caniuse.com/#feat=matchmedia).

**Comment by alichherawalla** [comment]
This has been taken care of in the latest release
https://github.com/wednesday-solutions/react-screentype-hook/blob/master/src/useScreenType.js#L20

**Comment by aarongarciah** [comment]
👍 

Just a heads up, `propTypes` are meant to be used with Components, not hooks.

https://github.com/wednesday-solutions/react-screentype-hook/blob/master/src/useScreenType.js#L54

**Comment by alichherawalla** [comment]
oh yeah! thanks, addressed it.
